package org.raku.nqp.sixmodel

import org.raku.nqp.runtime.ExceptionHandling
import org.raku.nqp.runtime.ThreadContext

/**
 * All 6model objects derive from this base class. A bunch of the REPR
 * API methods are also implemented through here. This is not the way
 * that 6model implementions in, say, C are factored. The spread of the
 * REPR API over REPR function tables and here is because this way is
 * a better fit and stands a better chance of performing well with the
 * way the JVM does things.
 */
abstract class SixModelObject : Cloneable {
    /**
     * The STable of the object. lateinit rather than nullable: every
     * allocation path assigns it immediately, but IndyBootstrap-created
     * stubs can leave it null on the Java side (Java reads the backing
     * field raw and does its own null checks; only Kotlin-side reads go
     * through the initialization check).
     */
    lateinit var st: STable

    /**
     * Raw null-check for st. Java and generated bytecode read the lateinit
     * backing field directly and see null on not-yet-filled stubs; a
     * Kotlin-side read of the property would throw
     * UninitializedPropertyAccessException instead, so code that must
     * tolerate stubs (IndyBootstrap's dispatch resolvers) checks this.
     */
    val stInitialized: Boolean
        get() = ::st.isInitialized

    /**
     * The serialization context this object belongs to, if any.
     */
    @JvmField var sc: SerializationContext? = null

    /**
     * Attribute access functions. The native variants load the value into
     * or store a value from the Thread Context.
     */
    open fun get_attribute_boxed(tc: ThreadContext, class_handle: SixModelObject?,
            name: String?, hint: Long): SixModelObject? {
        throw ExceptionHandling.dieInternal(tc, this.st.REPR.name + " representation does not support attributes")
    }
    open fun get_attribute_native(tc: ThreadContext, class_handle: SixModelObject?, name: String?, hint: Long) {
        throw ExceptionHandling.dieInternal(tc, this.st.REPR.name + " representation does not support natively typed attributes")
    }
    open fun bind_attribute_boxed(tc: ThreadContext, class_handle: SixModelObject?,
            name: String?, hint: Long, value: SixModelObject?) {
        throw ExceptionHandling.dieInternal(tc, this.st.REPR.name + " representation does not support attributes")
    }
    open fun bind_attribute_native(tc: ThreadContext, class_handle: SixModelObject?, name: String?, hint: Long) {
        throw ExceptionHandling.dieInternal(tc, this.st.REPR.name + " representation does not support natively typed attributes")
    }
    open fun is_attribute_initialized(tc: ThreadContext, class_handle: SixModelObject?,
            name: String?, hint: Long): Long {
        throw ExceptionHandling.dieInternal(tc, this.st.REPR.name + " representation does not support attributes")
    }
    open fun cas_attribute_boxed(tc: ThreadContext, class_handle: SixModelObject?,
            name: String?, expected: SixModelObject?, value: SixModelObject?): SixModelObject? {
        throw ExceptionHandling.dieInternal(tc, this.st.REPR.name + " representation does not support cas of attributes")
    }
    open fun atomic_bind_attribute_boxed(tc: ThreadContext, class_handle: SixModelObject?,
            name: String?, value: SixModelObject?) {
        throw ExceptionHandling.dieInternal(tc, this.st.REPR.name + " representation does not support atomic binding to attributes")
    }

    /**
     * Boxing related functions.
     */
    open fun set_int(tc: ThreadContext, value: Long) {
        throw ExceptionHandling.dieInternal(tc, "This type (" + this.st.REPR.name + ") cannot box a native integer")
    }
    open fun get_int(tc: ThreadContext): Long {
        throw ExceptionHandling.dieInternal(tc, "This type (" + this.st.REPR.name + ") cannot unbox to a native integer")
    }
    open fun set_num(tc: ThreadContext, value: Double) {
        throw ExceptionHandling.dieInternal(tc, "This type (" + this.st.REPR.name + ") cannot box a native number")
    }
    open fun get_num(tc: ThreadContext): Double {
        throw ExceptionHandling.dieInternal(tc, "This type (" + this.st.REPR.name + ") cannot unbox to a native number")
    }
    open fun set_str(tc: ThreadContext, value: String?) {
        throw ExceptionHandling.dieInternal(tc, "This type (" + this.st.REPR.name + ") cannot box a native string")
    }
    open fun get_str(tc: ThreadContext): String? {
        throw ExceptionHandling.dieInternal(tc, "This type (" + this.st.REPR.name + ") cannot unbox to a native string")
    }
    open fun set_boxing_of(tc: ThreadContext, reprId: Long, value: Any?) {
        throw ExceptionHandling.dieInternal(tc, this.st.REPR.name + " representation can not box "
            + REPRRegistry.getById(reprId.toInt()).name)
    }
    open fun get_boxing_of(tc: ThreadContext, reprId: Long): Any? {
        throw ExceptionHandling.dieInternal(tc, this.st.REPR.name + " representation can not unbox "
            + REPRRegistry.getById(reprId.toInt()).name)
    }

    /**
     * Positional access functions.
     */
    open fun at_pos_boxed(tc: ThreadContext, index: Long): SixModelObject? {
        throw ExceptionHandling.dieInternal(tc, this.st.REPR.name + " representation does not implement at_pos_boxed")
    }
    open fun at_pos_native(tc: ThreadContext, index: Long) {
        throw ExceptionHandling.dieInternal(tc, this.st.REPR.name + " representation does not implement at_pos_native")
    }
    open fun bind_pos_boxed(tc: ThreadContext, index: Long, value: SixModelObject?) {
        throw ExceptionHandling.dieInternal(tc, this.st.REPR.name + " representation does not implement bind_pos_boxed")
    }
    open fun bind_pos_native(tc: ThreadContext, index: Long) {
        throw ExceptionHandling.dieInternal(tc, this.st.REPR.name + " representation does not implement bind_pos_native")
    }
    open fun set_elems(tc: ThreadContext, count: Long) {
        throw ExceptionHandling.dieInternal(tc, this.st.REPR.name + " representation does not implement set_elems")
    }
    open fun exists_pos(tc: ThreadContext, key: Long): Long {
        throw ExceptionHandling.dieInternal(tc, this.st.REPR.name + " representation does not implement exists_pos")
    }
    open fun push_boxed(tc: ThreadContext, value: SixModelObject?) {
        throw ExceptionHandling.dieInternal(tc, this.st.REPR.name + " representation does not implement push_boxed")
    }
    open fun push_native(tc: ThreadContext) {
        throw ExceptionHandling.dieInternal(tc, this.st.REPR.name + " representation does not implement push_native")
    }
    open fun pop_boxed(tc: ThreadContext): SixModelObject? {
        throw ExceptionHandling.dieInternal(tc, this.st.REPR.name + " representation does not implement pop_boxed")
    }
    open fun pop_native(tc: ThreadContext) {
        throw ExceptionHandling.dieInternal(tc, this.st.REPR.name + " representation does not implement pop_native")
    }
    open fun unshift_boxed(tc: ThreadContext, value: SixModelObject?) {
        throw ExceptionHandling.dieInternal(tc, this.st.REPR.name + " representation does not implement unshift_boxed")
    }
    open fun unshift_native(tc: ThreadContext) {
        throw ExceptionHandling.dieInternal(tc, this.st.REPR.name + " representation does not implement unshift_native")
    }
    open fun shift_boxed(tc: ThreadContext): SixModelObject? {
        throw ExceptionHandling.dieInternal(tc, this.st.REPR.name + " representation does not implement shift_boxed")
    }
    open fun shift_native(tc: ThreadContext) {
        throw ExceptionHandling.dieInternal(tc, this.st.REPR.name + " representation does not implement shift_native")
    }
    open fun slice(tc: ThreadContext, dest: SixModelObject, beginning: Long, end: Long): SixModelObject? {
        throw ExceptionHandling.dieInternal(tc, this.st.REPR.name + " representation does not implement slice")
    }
    open fun splice(tc: ThreadContext, from: SixModelObject, offset: Long, count: Long) {
        throw ExceptionHandling.dieInternal(tc, this.st.REPR.name + " representation does not implement splice")
    }
    open fun at_pos_multidim_boxed(tc: ThreadContext, indices: LongArray): SixModelObject? {
        throw ExceptionHandling.dieInternal(tc, this.st.REPR.name + " representation does not implement at_pos_boxed_multidim")
    }
    open fun at_pos_multidim_native(tc: ThreadContext, indices: LongArray) {
        throw ExceptionHandling.dieInternal(tc, this.st.REPR.name + " representation does not implement at_pos_multidim_native")
    }
    open fun bind_pos_multidim_boxed(tc: ThreadContext, indices: LongArray, value: SixModelObject?) {
        throw ExceptionHandling.dieInternal(tc, this.st.REPR.name + " representation does not implement bind_pos_boxed_multidim")
    }
    open fun bind_pos_multidim_native(tc: ThreadContext, indices: LongArray) {
        throw ExceptionHandling.dieInternal(tc, this.st.REPR.name + " representation does not implement bind_pos_native_multidim")
    }
    open fun dimensions(tc: ThreadContext): LongArray {
        throw ExceptionHandling.dieInternal(tc, this.st.REPR.name + " representation does not implement dimensions")
    }
    open fun set_dimensions(tc: ThreadContext, dims: LongArray) {
        throw ExceptionHandling.dieInternal(tc, this.st.REPR.name + " representation does not implement set_dimensions")
    }

    /**
     * Associative access functions.
     */
    open fun at_key_boxed(tc: ThreadContext, key: String?): SixModelObject? {
        throw ExceptionHandling.dieInternal(tc, this.st.REPR.name + " representation does not implement at_key_boxed")
    }
    open fun at_key_native(tc: ThreadContext, key: String?) {
        throw ExceptionHandling.dieInternal(tc, this.st.REPR.name + " representation does not implement at_key_native")
    }
    open fun bind_key_boxed(tc: ThreadContext, key: String?, value: SixModelObject?) {
        throw ExceptionHandling.dieInternal(tc, this.st.REPR.name + " representation does not implement bind_key_boxed")
    }
    open fun bind_key_native(tc: ThreadContext, key: String?) {
        throw ExceptionHandling.dieInternal(tc, this.st.REPR.name + " representation does not implement bind_key_native")
    }
    open fun exists_key(tc: ThreadContext, key: String?): Long {
        throw ExceptionHandling.dieInternal(tc, this.st.REPR.name + " representation does not implement exists_key")
    }
    open fun delete_key(tc: ThreadContext, key: String?) {
        throw ExceptionHandling.dieInternal(tc, this.st.REPR.name + " representation does not implement delete_key")
    }

    /**
     * General aggregate-y operations.
     */
    open fun elems(tc: ThreadContext): Long {
        throw ExceptionHandling.dieInternal(tc, this.st.REPR.name + " representation does not implement elems")
    }

    /**
     * Clones the object.
     */
    open fun clone(tc: ThreadContext): SixModelObject {
        throw ExceptionHandling.dieInternal(tc, this.st.REPR.name + " representation does not implement cloning")
    }

    /* Kotlin would otherwise synthesize a public clone() with no throws
     * clause, which breaks the Java instance classes that wrap
     * this.clone() in a CloneNotSupportedException handler. */
    @Throws(CloneNotSupportedException::class)
    public override fun clone(): Any = super.clone()
}
