package org.raku.nqp.jast2bc;

import org.objectweb.asm.Opcodes;

/**
 * The class-file version for all runtime-generated bytecode: compilation
 * units emitted by the JAST compiler, and the classes generated at runtime
 * by BootJavaInterop, NativeCallOps and the P6Opaque/C-struct REPRs.
 *
 * Historically pinned at V1_7 (the ASM 4.1 era); modernized to V25 together
 * with the move to ASM 9.x and javac --release 25.
 */
public final class BytecodeVersion {
    public static final int EMITTED = Opcodes.V25;

    private BytecodeVersion() {}
}
