import java.io.File
import java.io.Writer

/**
 * Port of tools/build/gen-cat.pl: concatenates NQP sources, filtering
 * `#?if [!]stageN` / `#?if [!]<backend>` / `#?endif` preprocessor blocks.
 * Output is byte-identical to the perl script (verified by genCatParityCheck).
 */
object GenCat {
    private val ifStageRe = Regex("""^#\?if\s+(!)?\s*(stage\d)\s*$""")
    private val ifBackendRe = Regex("""^#\?if\s+(!)?\s*(\w+)\s*$""")
    private val endifRe = Regex("""^#\?endif\s*$""")

    // gen-cat.pl replaces an unrecognized stage argument with a value that
    // matches no #?if stageN tag; "asdfgh" is the literal it uses.
    const val NO_STAGE = "asdfgh"

    fun concat(backend: String, stage: String, sources: List<Pair<String, File>>, out: Writer) {
        out.write("# This file automatically generated by nqp's tools/build/gen-cat.pl\n\n")
        for ((label, file) in sources) {
            out.write("#line 1 NQP::$label\n")
            var omit = false
            val conds = ArrayDeque<Boolean>()
            val text = file.readText(Charsets.UTF_8)
            var idx = 0
            while (idx < text.length) {
                val nl = text.indexOf('\n', idx)
                val line: String
                val hasNewline: Boolean
                if (nl >= 0) {
                    line = text.substring(idx, nl)
                    hasNewline = true
                    idx = nl + 1
                } else {
                    line = text.substring(idx)
                    hasNewline = false
                    idx = text.length
                }
                val mStage = ifStageRe.matchEntire(line)
                val mBackend = if (mStage == null) ifBackendRe.matchEntire(line) else null
                when {
                    mStage != null -> {
                        conds.addLast(omit)
                        val neg = mStage.groupValues[1] == "!"
                        val tag = mStage.groupValues[2]
                        omit = omit || (neg && tag == stage || !neg && tag != stage)
                    }
                    mBackend != null -> {
                        conds.addLast(omit)
                        val neg = mBackend.groupValues[1] == "!"
                        val tag = mBackend.groupValues[2]
                        omit = omit || (neg && tag == backend || !neg && tag != backend)
                    }
                    endifRe.matches(line) -> omit = if (conds.isEmpty()) false else conds.removeLast()
                    !omit -> {
                        out.write(line)
                        if (hasNewline) out.write("\n")
                    }
                }
            }
        }
        out.write("\n# vim: set ft=perl6 nomodifiable :\n")
    }
}
