import org.gradle.api.DefaultTask
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.ListProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction

/**
 * Generates the build-tree runner script (nqp-j-gradle), mirroring
 * tools/templates/jvm/nqp-j.in. Unlike the Makefile's nqp-j (which uses paths
 * relative to the checkout root plus `.` entries), this runner bakes absolute
 * paths into the Gradle output layout, so it works from any directory and
 * never picks up artifacts of the parallel Makefile build.
 */
abstract class GenerateRunnerTask : DefaultTask() {
    /** Absolute path of the directory holding nqp-runtime.jar + third-party jars. */
    @get:Input
    abstract val jarDir: Property<String>

    /** Absolute path of the directory holding nqp.jar and the module jars. */
    @get:Input
    abstract val libDir: Property<String>

    /** Third-party jar file names, in runner bootclasspath order (no asm-tree). */
    @get:Input
    abstract val runnerJarNames: ListProperty<String>

    @get:OutputFile
    abstract val output: RegularFileProperty

    @TaskAction
    fun run() {
        val jar = jarDir.get()
        val lib = libDir.get()
        val bootEntries = buildList {
            add(lib)
            add("$jar/nqp-runtime.jar")
            runnerJarNames.get().forEach { add("$jar/$it") }
            add("$lib/nqp.jar")
        }
        val script = """
            |#!/bin/sh
            |
            |# Generated by the Gradle build (see build.gradle.kts); mirrors
            |# tools/templates/jvm/nqp-j.in with absolute paths.
            |
            |# Sourced from https://stackoverflow.com/a/29835459/1975049
            |rreadlink() (
            |  target=${'$'}1 fname= targetDir= CDPATH=
            |  { \unalias command; \unset -f command; } >/dev/null 2>&1
            |  [ -n "${'$'}ZSH_VERSION" ] && options[POSIX_BUILTINS]=on
            |  while :; do
            |      [ -L "${'$'}target" ] || [ -e "${'$'}target" ] || { command printf '%s\n' "ERROR: '${'$'}target' does not exist." >&2; return 1; }
            |      command cd "${'$'}(command dirname -- "${'$'}target")"
            |      fname=${'$'}(command basename -- "${'$'}target")
            |      [ "${'$'}fname" = '/' ] && fname=''
            |      if [ -L "${'$'}fname" ]; then
            |        target=${'$'}(command ls -l "${'$'}fname")
            |        target=${'$'}{target#* -> }
            |        continue
            |      fi
            |      break
            |  done
            |  targetDir=${'$'}(command pwd -P)
            |  if [ "${'$'}fname" = '.' ]; then
            |    command printf '%s\n' "${'$'}{targetDir%/}"
            |  elif  [ "${'$'}fname" = '..' ]; then
            |    command printf '%s\n' "${'$'}(command dirname -- "${'$'}{targetDir}")"
            |  else
            |    command printf '%s\n' "${'$'}{targetDir%/}/${'$'}fname"
            |  fi
            |)
            |
            |EXEC=${'$'}(rreadlink "${'$'}0")
            |
            |# --enable-native-access: JNA loads its dispatch library via
            |# System.load, which JDK 24+ warns about (JEP 472) and will
            |# eventually block for code without native access enabled.
            |#
            |# NQP_JVM_MAXHEAP caps the heap (default 4g). The Makefile runner
            |# uses -XX:+AggressiveHeap (~half of physical RAM per JVM), which
            |# can stall a swapless machine when several runners overlap.
            |exec java -Dnqp.execname="${'$'}EXEC" --enable-native-access=ALL-UNNAMED -Xmx"${'$'}{NQP_JVM_MAXHEAP:-4g}" -XX:+AllowParallelDefineClass -Xbootclasspath/a:"${bootEntries.joinToString(":")}" -cp "$lib" nqp "${'$'}@"
            |""".trimMargin()
        val file = output.get().asFile
        file.writeText(script)
        file.setExecutable(true, false)
    }
}
