import org.gradle.api.DefaultTask
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.ListProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.Optional
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction

/**
 * Generates the build-tree runner script (nqp-j-gradle), mirroring
 * tools/templates/jvm/nqp-j.in. Unlike the Makefile's nqp-j (which uses paths
 * relative to the checkout root plus `.` entries), this runner bakes absolute
 * paths into the Gradle output layout, so it works from any directory and
 * never picks up artifacts of the parallel Makefile build.
 */
abstract class GenerateRunnerTask : DefaultTask() {
    /** Absolute path of the directory holding nqp-runtime.jar + third-party jars. */
    @get:Input
    abstract val jarDir: Property<String>

    /** Absolute path of the directory holding nqp.jar and the module jars. */
    @get:Input
    abstract val libDir: Property<String>

    /** Third-party jar file names, in runner bootclasspath order (no asm-tree). */
    @get:Input
    abstract val runnerJarNames: ListProperty<String>

    /**
     * Absolute path of the directory holding the Truffle module jars, and of
     * the grammar engine's own jar. The engine goes on the CLASS path, not
     * the boot classpath: it needs to see Truffle, and the boot loader cannot
     * see the module path. It can still call into nqp-runtime, because the
     * application loader delegates to the boot loader; the return trip is why
     * the runtime looks the engine up reflectively rather than importing it.
     */
    @get:[Input Optional]
    abstract val truffleModuleDir: Property<String>

    @get:[Input Optional]
    abstract val engineJar: Property<String>

    @get:OutputFile
    abstract val output: RegularFileProperty

    @TaskAction
    fun run() {
        val jar = jarDir.get()
        val lib = libDir.get()
        val bootEntries = buildList {
            add(lib)
            add("$jar/nqp-runtime.jar")
            runnerJarNames.get().forEach { add("$jar/$it") }
            add("$lib/nqp.jar")
        }
        // Emitted only when both halves are staged, so a tree built without
        // the engine still produces a runner that works.
        val truffleSetup = if (truffleModuleDir.isPresent && engineJar.isPresent) {
            """
            |# The grammar engine runs on Truffle, which binds to the JDK's
            |# compiler only when its jars resolve as MODULES; on the class
            |# path it falls back to an interpreter that does no partial
            |# evaluation and simply measures as "Truffle is slow".
            |#
            |# The engine jar goes on the class path rather than the boot
            |# classpath because the boot loader cannot see the module path.
            |# Every regex and (with NQP_CODE_RUN) every block runs on it:
            |# there is no bytecode regex path to fall back to.
            |TRUFFLE="--module-path ${truffleModuleDir.get()} --add-modules org.graalvm.truffle,org.graalvm.truffle.runtime"
            |TRUFFLE_NATIVE=",org.graalvm.truffle"
            |CP="$lib:${engineJar.get()}"
            |""".trimMargin()
        } else {
            """
            |TRUFFLE=
            |TRUFFLE_NATIVE=
            |CP="$lib"
            |""".trimMargin()
        }
        val script = """
            |#!/bin/sh
            |
            |# Generated by the Gradle build (see build.gradle.kts); mirrors
            |# tools/templates/jvm/nqp-j.in with absolute paths.
            |
            |# Sourced from https://stackoverflow.com/a/29835459/1975049
            |rreadlink() (
            |  target=${'$'}1 fname= targetDir= CDPATH=
            |  { \unalias command; \unset -f command; } >/dev/null 2>&1
            |  [ -n "${'$'}ZSH_VERSION" ] && options[POSIX_BUILTINS]=on
            |  while :; do
            |      [ -L "${'$'}target" ] || [ -e "${'$'}target" ] || { command printf '%s\n' "ERROR: '${'$'}target' does not exist." >&2; return 1; }
            |      command cd "${'$'}(command dirname -- "${'$'}target")"
            |      fname=${'$'}(command basename -- "${'$'}target")
            |      [ "${'$'}fname" = '/' ] && fname=''
            |      if [ -L "${'$'}fname" ]; then
            |        target=${'$'}(command ls -l "${'$'}fname")
            |        target=${'$'}{target#* -> }
            |        continue
            |      fi
            |      break
            |  done
            |  targetDir=${'$'}(command pwd -P)
            |  if [ "${'$'}fname" = '.' ]; then
            |    command printf '%s\n' "${'$'}{targetDir%/}"
            |  elif  [ "${'$'}fname" = '..' ]; then
            |    command printf '%s\n' "${'$'}(command dirname -- "${'$'}{targetDir}")"
            |  else
            |    command printf '%s\n' "${'$'}{targetDir%/}/${'$'}fname"
            |  fi
            |)
            |
            |EXEC=${'$'}(rreadlink "${'$'}0")
            |
            |# --enable-native-access: the native call support links foreign
            |# functions with java.lang.foreign, whose restricted methods JDK
            |# 24+ warns about (JEP 472) and will eventually refuse to code
            |# that has not been granted native access. Truffle is a NAMED
            |# module, so ALL-UNNAMED does not cover it and it has to be
            |# granted access by name -- the JVM says as much in the warning.
            |#
            |# --sun-misc-unsafe-memory-access=allow: Truffle's own runtime
            |# calls the terminally deprecated Unsafe::objectFieldOffset. That
            |# is in truffle-runtime, not in anything here; NQP itself moved
            |# off the Unsafe fast path to safeInstance() already. Nothing to
            |# fix on this side, so quieten it rather than print it per run.
            |#
            |# NQP_JVM_MAXHEAP caps the heap (default 4g). The Makefile runner
            |# uses -XX:+AggressiveHeap (~half of physical RAM per JVM), which
            |# can stall a swapless machine when several runners overlap.
            |#
            |# -Xss64m: grammar rules recurse one Java frame chain per rule
            |# nesting level, and a big enough source (rakudo's RakuAST class
            |# files, parsed by raku-ast-compiler.nqp) overflows the default
            |# main-thread stack -- sometimes, since frame sizes depend on
            |# what the JIT has gotten to. Rakudo's runners have carried the
            |# same flag since its VarLowering overflowed the same way.
            |$truffleSetup
            |exec java -Dnqp.execname="${'$'}EXEC" --enable-native-access=ALL-UNNAMED${'$'}{TRUFFLE_NATIVE} --sun-misc-unsafe-memory-access=allow -Xmx"${'$'}{NQP_JVM_MAXHEAP:-4g}" -Xss64m -XX:+AllowParallelDefineClass ${'$'}TRUFFLE -Xbootclasspath/a:"${bootEntries.joinToString(":")}" -cp "${'$'}CP" org.raku.nqp.runtime.unit.UnitMain "$lib/nqp.jar" "${'$'}@"
            |""".trimMargin()
        val file = output.get().asFile
        file.writeText(script)
        file.setExecutable(true, false)
    }
}
