import org.gradle.api.DefaultTask
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.ListProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.Optional
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction

/**
 * Generates the build-tree runner script (nqp-j-gradle), mirroring
 * tools/templates/jvm/nqp-j.in. Unlike the Makefile's nqp-j (which uses paths
 * relative to the checkout root plus `.` entries), this runner bakes absolute
 * paths into the Gradle output layout, so it works from any directory and
 * never picks up artifacts of the parallel Makefile build.
 */
abstract class GenerateRunnerTask : DefaultTask() {
    /** Absolute path of the directory holding nqp-runtime.jar + third-party jars. */
    @get:Input
    abstract val jarDir: Property<String>

    /** Absolute path of the directory holding nqp.jar and the module jars. */
    @get:Input
    abstract val libDir: Property<String>

    /** Third-party jar file names, in runner class path order. */
    @get:Input
    abstract val runnerJarNames: ListProperty<String>

    /**
     * Absolute path of the directory holding the Truffle module jars, and of
     * the grammar engine's own jar. Every jar goes on the CLASS path (nothing
     * on the boot class path since 7b, milestone 7), and the engine needs the
     * Truffle jars on the MODULE path as well: Truffle binds to the JDK's
     * compiler only when its own jars resolve as modules.
     */
    @get:[Input Optional]
    abstract val truffleModuleDir: Property<String>

    @get:[Input Optional]
    abstract val engineJar: Property<String>

    @get:OutputFile
    abstract val output: RegularFileProperty

    /**
     * The eval server twin of [output]: the same JVM setup running
     * org.raku.nqp.tools.EvalServer, behind the memory guard rakudo's
     * rakudo-eval-server carries (tools/build/create-jvm-runner.pl there).
     */
    @get:[OutputFile Optional]
    abstract val evalServerOutput: RegularFileProperty

    @TaskAction
    fun run() {
        val jar = jarDir.get()
        val lib = libDir.get()
        val classPathEntries = buildList {
            add(lib)
            add("$jar/nqp-runtime.jar")
            runnerJarNames.get().forEach { add("$jar/$it") }
            add("$lib/nqp.jar")
        }
        // Emitted only when both halves are staged, so a tree built without
        // the engine still produces a runner that works.
        val truffleSetup = if (truffleModuleDir.isPresent && engineJar.isPresent) {
            """
            |# The grammar engine runs on Truffle, which binds to the JDK's
            |# compiler only when its jars resolve as MODULES; on the class
            |# path it falls back to an interpreter that does no partial
            |# evaluation and simply measures as "Truffle is slow".
            |#
            |# Every jar is on the class path (nothing on the boot class
            |# path since milestone 7, 7b): a runtime-tree @TruffleBoundary
            |# must be visible to the compiler, and the boot loader cannot
            |# see the module path either.
            |# Every regex and every block runs on it (the encoder is always
            |# on since milestone 3):
            |# there is no bytecode regex path to fall back to.
            |TRUFFLE="--module-path ${truffleModuleDir.get()} --add-modules org.graalvm.truffle,org.graalvm.truffle.runtime"
            |TRUFFLE_NATIVE=",org.graalvm.truffle"
            |CP="$lib:${engineJar.get()}"
            |""".trimMargin()
        } else {
            """
            |TRUFFLE=
            |TRUFFLE_NATIVE=
            |CP="$lib"
            |""".trimMargin()
        }
        fun render(prelude: String, launch: String) = """
            |#!/bin/sh
            |
            |# Generated by the Gradle build (see build.gradle.kts); mirrors
            |# tools/templates/jvm/nqp-j.in with absolute paths.
            |
            |# Sourced from https://stackoverflow.com/a/29835459/1975049
            |rreadlink() (
            |  target=${'$'}1 fname= targetDir= CDPATH=
            |  { \unalias command; \unset -f command; } >/dev/null 2>&1
            |  [ -n "${'$'}ZSH_VERSION" ] && options[POSIX_BUILTINS]=on
            |  while :; do
            |      [ -L "${'$'}target" ] || [ -e "${'$'}target" ] || { command printf '%s\n' "ERROR: '${'$'}target' does not exist." >&2; return 1; }
            |      command cd "${'$'}(command dirname -- "${'$'}target")"
            |      fname=${'$'}(command basename -- "${'$'}target")
            |      [ "${'$'}fname" = '/' ] && fname=''
            |      if [ -L "${'$'}fname" ]; then
            |        target=${'$'}(command ls -l "${'$'}fname")
            |        target=${'$'}{target#* -> }
            |        continue
            |      fi
            |      break
            |  done
            |  targetDir=${'$'}(command pwd -P)
            |  if [ "${'$'}fname" = '.' ]; then
            |    command printf '%s\n' "${'$'}{targetDir%/}"
            |  elif  [ "${'$'}fname" = '..' ]; then
            |    command printf '%s\n' "${'$'}(command dirname -- "${'$'}{targetDir}")"
            |  else
            |    command printf '%s\n' "${'$'}{targetDir%/}/${'$'}fname"
            |  fi
            |)
            |
            |EXEC=${'$'}(rreadlink "${'$'}0")
            |
            |# --enable-native-access: the native call support links foreign
            |# functions with java.lang.foreign, whose restricted methods JDK
            |# 24+ warns about (JEP 472) and will eventually refuse to code
            |# that has not been granted native access. Truffle is a NAMED
            |# module, so ALL-UNNAMED does not cover it and it has to be
            |# granted access by name -- the JVM says as much in the warning.
            |#
            |# --sun-misc-unsafe-memory-access=allow: Truffle's own runtime
            |# calls the terminally deprecated Unsafe::objectFieldOffset. That
            |# is in truffle-runtime, not in anything here; NQP itself moved
            |# off the Unsafe fast path to safeInstance() already. Nothing to
            |# fix on this side, so quieten it rather than print it per run.
            |#
            |# NQP_JVM_MAXHEAP caps the heap (default 4g). The Makefile runner
            |# uses -XX:+AggressiveHeap (~half of physical RAM per JVM), which
            |# can stall a swapless machine when several runners overlap.
            |#
            |# -Xss64m: grammar rules recurse one Java frame chain per rule
            |# nesting level, and a big enough source (rakudo's RakuAST class
            |# files, parsed by raku-ast-compiler.nqp) overflows the default
            |# main-thread stack -- sometimes, since frame sizes depend on
            |# what the JIT has gotten to. Rakudo's runners have carried the
            |# same flag since its VarLowering overflowed the same way.
            |$truffleSetup
            |$prelude
            |exec $launch
            |""".trimMargin()

        // Everything on the class path, as rakudo-j has it: a class on the
        // boot class path cannot resolve a Truffle annotation type, so a
        // @TruffleBoundary in the runtime tree was invisible under these
        // runners (milestone 7, Task 7b).
        val jvmOpts = "--enable-native-access=ALL-UNNAMED${'$'}{TRUFFLE_NATIVE}" +
            " --sun-misc-unsafe-memory-access=allow -Xss64m -XX:+AllowParallelDefineClass" +
            " ${'$'}TRUFFLE -cp \"${classPathEntries.joinToString(":")}:${'$'}CP\""
        write(output, render("",
            "java -Dnqp.execname=\"${'$'}EXEC\" -Xmx\"${'$'}{NQP_JVM_MAXHEAP:-4g}\" $jvmOpts" +
                " org.raku.nqp.runtime.unit.UnitMain \"$lib/nqp.jar\" \"${'$'}@\""))
        if (evalServerOutput.isPresent) {
            // G1 uncommit: without it a server's RSS stays at its allocation
            // high-water mark between runs while little is live.
            val g1 = "-XX:MinHeapFreeRatio=15 -XX:MaxHeapFreeRatio=40" +
                " -XX:G1PeriodicGCInterval=20000 -XX:-G1PeriodicGCInvokesConcurrent"
            // nqp::execname is what a run spawns to start another nqp, so it
            // names the plain runner next to this script, not the server.
            val runner = output.get().asFile.name
            write(evalServerOutput, render(EVAL_SERVER_GUARD,
                "${'$'}cage java -Dnqp.execname=\"${'$'}{EXEC%/*}/$runner\" -Xmx${'$'}heap $g1 $jvmOpts" +
                    " org.raku.nqp.tools.EvalServer \"${'$'}@\""))
        }
    }

    private fun write(target: RegularFileProperty, script: String) {
        val file = target.get().asFile
        file.writeText(script)
        file.setExecutable(true, false)
    }

    private companion object {
        /**
         * Mirrors the guard in rakudo's create-jvm-runner.pl. Several servers
         * at once have taken the machine down (the OOM killer fires late on a
         * swapless box and takes the terminal's cgroup with it), so the
         * launcher refuses when this server's ceiling plus the room every live
         * EvalServer -- nqp's or rakudo's, pgrep matches the class -- can still
         * grow into exceeds MemAvailable, and cages the JVM in its own scope.
         * The 3g overhead is libgraal's native JIT isolate plus metaspace and
         * stacks, all outside -Xmx.
         */
        val EVAL_SERVER_GUARD = """
            |# Children a test spawns (nqp-j-gradle via nqp::execname) inherit
            |# this environment and would each take a 4g heap inside this cage.
            |export NQP_JVM_MAXHEAP="${'$'}{NQP_JVM_CHILD_HEAP:-2g}"
            |
            |# Memory guard: see GenerateRunnerTask.kt. Do not bypass it --
            |# lower NQP_EVALSERVER_HEAP or stop a server instead.
            |heap="${'$'}{NQP_EVALSERVER_HEAP:=8g}"
            |mb_of() { case "${'$'}1" in *[gG]) echo ${'$'}(( ${'$'}{1%[gG]} * 1024 )) ;; *[mM]) echo "${'$'}{1%[mM]}" ;; *[kK]) echo ${'$'}(( ${'$'}{1%[kK]} / 1024 )) ;; *) echo ${'$'}(( ${'$'}1 / 1048576 )) ;; esac; }
            |OVERHEAD_MB=3072
            |need=${'$'}(( ${'$'}(mb_of "${'$'}heap") + OVERHEAD_MB ))
            |if [ -r /proc/meminfo ]; then
            |    avail=${'$'}(awk '/^MemAvailable:/ { print int(${'$'}2 / 1024) }' /proc/meminfo)
            |    live=0; grow=0
            |    for pid in ${'$'}(pgrep -f 'org\.raku\.nqp\.tools\.EvalServer' 2>/dev/null); do
            |        xmx=${'$'}(tr '\0' ' ' < /proc/${'$'}pid/cmdline 2>/dev/null | sed -n 's/.*-Xmx\([0-9]*[gGmMkK]\{0,1\}\) .*/\1/p')
            |        [ -n "${'$'}xmx" ] || continue
            |        rss=${'$'}(awk '/^VmRSS:/ { print int(${'$'}2 / 1024) }' /proc/${'$'}pid/status 2>/dev/null)
            |        room=${'$'}(( ${'$'}(mb_of "${'$'}xmx") + OVERHEAD_MB - ${'$'}{rss:-0} ))
            |        [ "${'$'}room" -gt 0 ] && grow=${'$'}(( grow + room ))
            |        live=${'$'}(( live + 1 ))
            |    done
            |    if [ ${'$'}(( need + grow )) -gt "${'$'}avail" ]; then
            |        echo "nqp-eval-server: REFUSING to start." >&2
            |        echo "  this server may grow to ${'$'}{need}m (heap ${'$'}heap + ${'$'}{OVERHEAD_MB}m off-heap)," >&2
            |        echo "  the ${'$'}live live server(s) may still grow by ${'$'}{grow}m, MemAvailable is ${'$'}{avail}m." >&2
            |        echo "  Stop a server or set NQP_EVALSERVER_HEAP lower. Do not work around this check." >&2
            |        exit 75
            |    fi
            |fi
            |cage=""
            |if command -v systemd-run >/dev/null 2>&1 && systemd-run --user --scope --quiet -- true >/dev/null 2>&1; then
            |    cage="systemd-run --user --scope --quiet -p MemoryMax=${'$'}{need}M --"
            |fi
            |""".trimMargin()
    }
}
