import org.gradle.api.DefaultTask
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.ListProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction
import org.gradle.process.ExecOperations
import java.io.ByteArrayOutputStream
import java.io.File
import javax.inject.Inject

/**
 * Port of tools/build/gen-jvm-properties.pl. Assembles the jvmconfig.properties
 * resource read at runtime by Ops.jvmgetconfig(). The nativecall.* keys come
 * from Perl's Config module (they describe the C toolchain perl was built
 * with); we shell out to perl once for them, exactly as the original did.
 *
 * Not @CacheableTask: output embeds host perl -MConfig state.
 */
abstract class JvmConfigPropertiesTask : DefaultTask() {
    /** "." for the in-tree copy, or the install prefix. */
    @get:Input
    abstract val prefix: Property<String>

    /** STATIC_NQP_HOME, e.g. <prefix>/share/nqp. */
    @get:Input
    abstract val nqpHome: Property<String>

    /** Absolute paths of the third-party jars, in classpath order. */
    @get:Input
    abstract val thirdPartyJars: ListProperty<String>

    /** Path printed in the "generated by" header (kept identical to the perl build). */
    @get:Input
    abstract val generatorLabel: Property<String>

    @get:OutputFile
    abstract val output: RegularFileProperty

    @get:Inject
    abstract val execOps: ExecOperations

    @TaskAction
    fun run() {
        val cpsep = File.pathSeparator
        val slash = File.separator
        var jardir = "."
        var libdir = "."
        var jars = thirdPartyJars.get()
        if (prefix.get() != ".") {
            jardir = nqpHome.get() + slash + "runtime"
            libdir = nqpHome.get() + slash + "lib"
            jars = jars.map { jardir + slash + File(it).name }
        }
        val allJars = jars.joinToString(cpsep) +
            "$cpsep$jardir${slash}nqp-runtime.jar$cpsep$libdir${slash}nqp.jar"

        /*
         * Where the grammar engine lives, for anything downstream that has to
         * start a JVM able to run NQP-compiled code. Rakudo is the case that
         * matters: nqp.jar now holds rules compiled to descriptors, and a
         * runner that loads it without these cannot run them at all. The
         * modules must be on the MODULE path and the engine on the class
         * path -- see GrammarEngine.kt for why the split is not optional.
         */
        val truffledir = if (prefix.get() == ".") "." else nqpHome.get() + slash + "truffle"

        val configKeys = listOf(
            "_o", "so", "cc", "ccflags", "cccdlflags", "ccdlflags",
            "ld", "ldflags", "lddlflags", "libs", "perllibs", "osname",
        )
        val stdout = ByteArrayOutputStream()
        execOps.exec {
            commandLine(
                "perl", "-MConfig", "-e",
                configKeys.joinToString(
                    prefix = "print join(\"\\0\", map { defined \$Config{\$_} ? \$Config{\$_} : '' } qw(",
                    separator = " ",
                    postfix = ")), \"\\0\", \$^O;",
                ),
            )
            standardOutput = stdout
        }
        val values = stdout.toString(Charsets.UTF_8).split('\u0000')
        val cfg = configKeys.zip(values).toMap()
        val osName = values.last()
        val ccdlflags = "${cfg["cccdlflags"]} ${cfg["ccdlflags"]}"
        val ldout = if (osName == "MSWin32") "-out:" else "-o"

        output.get().asFile.writeText(
            """
            |# This file automatically generated by ${generatorLabel.get()}
            |
            |prefix=${prefix.get()}
            |runtime.bootclasspath=-Xbootclasspath/a:.$cpsep$allJars
            |runtime.classpath=$libdir
            |runtime.jars=$allJars
            |runtime.truffle.modulepath=$truffledir
            |runtime.truffle.addmodules=org.graalvm.truffle,org.graalvm.truffle.runtime
            |runtime.truffle.engine=$jardir${slash}nqp-truffle.jar
            |nativecall.o=${cfg["_o"]}
            |nativecall.so=${cfg["so"]}
            |nativecall.cc=${cfg["cc"]}
            |nativecall.ccflags=${cfg["ccflags"]}
            |nativecall.ccdlflags=$ccdlflags
            |nativecall.ld=${cfg["ld"]}
            |nativecall.ldout=$ldout
            |nativecall.ldflags=${cfg["ldflags"]}
            |nativecall.lddlflags=${cfg["lddlflags"]}
            |nativecall.libs=${cfg["libs"]}
            |nativecall.perllibs=${cfg["perllibs"]}
            |osname=$osName
            |""".trimMargin(),
            Charsets.UTF_8,
        )
    }
}
