package org.raku.nqp.runtime

import org.objectweb.asm.Opcodes

/**
 * The class-file version for all runtime-generated bytecode: the plain
 * classes generated at runtime by BootJavaInterop, NativeCallOps and the
 * P6Opaque/C-struct REPRs.
 *
 * Historically pinned at V1_7 (the ASM 4.1 era); modernized to V25 together
 * with the move to ASM 9.x and javac --release 25.
 */
object BytecodeVersion {
    const val EMITTED = Opcodes.V25
}
