package org.raku.nqp.runtime

import org.raku.nqp.sixmodel.SixModelObject

/**
 * The bytecode side of the Truffle grammar engine.
 *
 * The two halves cannot see each other directly. nqp-runtime is on the boot
 * classpath, because generated bytecode has to resolve against it; the engine
 * is on the class path, because Truffle only binds to the JDK's compiler when
 * its jars resolve as modules and the boot loader cannot see the module path.
 * The application loader delegates to the boot loader, so the engine calls
 * into the runtime by ordinary reference -- but the runtime cannot name the
 * engine at all. This interface is the way back: declared here where both
 * loaders can see it, implemented over there, and reached through
 * [GrammarEngines.get], which looks the implementation up by name.
 */
interface GrammarEngine {
    /**
     * Turns one regex descriptor into a program that can be matched.
     *
     * Called once per regex rather than once per match: the descriptor is
     * fixed at compile time, and building the Truffle tree is the expensive
     * half. The result is opaque here, and is handed back to [match].
     */
    fun compile(encoded: String): Any

    /**
     * Matches [program] against [target] starting at [from].
     *
     * The start position is passed rather than read off the cursor: a cursor
     * `!cursor_start_all` has just built carries `$!pos` of -3 until the rule
     * finishes, so the only honest source is the same list the bytecode
     * prologue takes it from.
     *
     * Answers the cursor, having done to it exactly what the compiled
     * bytecode would: `!cursor_pass` at the matched position -- with the
     * rule's name, when it has one, so that it reduces -- or `!cursor_fail`
     * when nothing matched.
     */
    fun match(
        program: Any,
        tc: ThreadContext,
        cursor: SixModelObject,
        cursorClass: SixModelObject,
        target: String,
        from: Int,
        invocantFrom: Int,
        callback: SixModelObject?,
    ): SixModelObject
}

/**
 * Finds the grammar engine, or establishes that there isn't one.
 *
 * A missing engine is a supported state, not an error: a regex whose shape
 * the engine does not cover keeps the bytecode path, and so does every regex
 * when `NQP_JVM_NO_TRUFFLE` is set. What is *not* supported is an engine that
 * quietly fails to load and leaves everything looking merely slow, so
 * anything other than a plain absence is reported, and `NQP_JVM_TRUFFLE=require`
 * turns absence itself into a failure -- which is what a benchmark or a test
 * that means to measure the engine should set.
 */
object GrammarEngines {
    private const val IMPL = "org.raku.nqp.truffle.TruffleGrammarEngine"

    private val required: Boolean = System.getenv("NQP_JVM_TRUFFLE") == "require"

    private val engine: GrammarEngine? by lazy { load() }

    /**
     * The compiled program for each descriptor, by descriptor.
     *
     * Compiling is per regex and matching is per rule per position, so this
     * exists to keep the two apart. The key is the descriptor itself, which
     * the class file already holds as a constant, so identical rules in
     * different classes share one compiled program.
     */
    private val programs = java.util.concurrent.ConcurrentHashMap<String, Any>()

    /**
     * Traces every match to stderr as `rx <rule> <from>..<end>`.
     *
     * This is a RUN time switch, not a compile time one, which is the whole
     * point of it: the descriptors are already in the class files, so a
     * question about which rule matched wrongly can be answered by running
     * the thing again rather than by rebuilding NQP to ask it. `<anon>`
     * stands for a rule that does not reduce, and `-1` for no match.
     */
    private val trace: Boolean = System.getenv("NQP_RX_TRACE") != null

    /** The engine, or null when regexes should take the bytecode path. */
    @JvmStatic
    fun get(): GrammarEngine? = engine

    /**
     * Matches one compiled regex; the entry point generated code calls.
     *
     * Whether a regex reaches here at all was settled when it was compiled:
     * a rule the engine covers has no bytecode matcher to fall back to, so
     * a missing engine here is a real error rather than a slower path. That
     * is why `NQP_JVM_NO_TRUFFLE` has to be set for the compile and the run
     * alike -- it decides whether descriptors are emitted in the first place,
     * and a tree compiled with them cannot be run without the engine.
     */
    @JvmStatic
    fun rxmatch(
        encoded: String,
        cursor: SixModelObject,
        cursorClass: SixModelObject,
        target: String,
        from: Long,
        invocantFrom: Long,
        callback: SixModelObject?,
        tc: ThreadContext,
    ): SixModelObject {
        val engine = engine ?: throw IllegalStateException(
            "this code was compiled with the grammar engine, which is not available at run time." +
            " NQP_JVM_NO_TRUFFLE has to be set for the compile and the run alike, or for neither.")
        val program = programs.computeIfAbsent(encoded) { engine.compile(it) }
        if (trace) traceEnter(encoded, target, from)
        val result = engine.match(
            program, tc, cursor, cursorClass, target, from.toInt(), invocantFrom.toInt(),
            callback)
        if (trace) traceLeave(encoded, cursor, cursorClass, from, tc)
        return result
    }

    /**
     * Entry and exit are traced separately because a rule can leave without
     * returning: a subrule like `<.panic: ...>` throws, and the exception
     * unwinds straight through. Tracing only the return makes such a rule
     * invisible, which reads as "the engine was not involved" -- the exact
     * wrong conclusion. A `>` with no matching `<` is the rule that threw.
     */
    private fun traceEnter(encoded: String, target: String, from: Long) {
        val where = if (from < target.length) target.substring(
            from.toInt(), minOf(target.length, from.toInt() + 12)) else ""
        System.err.println("rx> %-28s %4d      %s".format(
            label(encoded), from, where.replace("\n", "\\n")))
    }

    private fun traceLeave(
        encoded: String,
        cursor: SixModelObject,
        cursorClass: SixModelObject,
        from: Long,
        tc: ThreadContext,
    ) {
        val pos = Ops.getattr_i(cursor, cursorClass, "\$!pos", tc)
        System.err.println("rx< %-28s %4d..%-4d %s".format(
            label(encoded), from, pos, if (pos < 0) "FAIL" else ""))
    }

    /** A rule's name, or a stable short id when it does not reduce. */
    private fun label(encoded: String): String {
        val name = passNameOf(encoded)
        return if (name.isNotEmpty()) name
               else "<anon %08x>".format(encoded.hashCode())
    }

    /**
     * The rule name off the end of a descriptor, which ends `<len>:<name>`.
     *
     * Taking everything after the last colon would be wrong: plenty of rule
     * names contain one (`directive:sym<a>`), and that would report `sym<a>`.
     * The length prefix says exactly how many characters the name has, so it
     * is the thing to trust.
     */
    private fun passNameOf(encoded: String): String {
        val colon = encoded.lastIndexOf(':')
        if (colon < 0) return ""
        var at = colon
        while (at > 0 && encoded[at - 1].isDigit()) at--
        val len = encoded.substring(at, colon).toIntOrNull() ?: return ""
        val name = encoded.substring(colon + 1)
        return if (name.length == len) name else ""
    }

    private fun load(): GrammarEngine? {
        if (System.getenv("NQP_JVM_NO_TRUFFLE") != null) {
            check(!required) { "NQP_JVM_TRUFFLE=require conflicts with NQP_JVM_NO_TRUFFLE" }
            return null
        }
        try {
            val cls = Class.forName(IMPL, true, ClassLoader.getSystemClassLoader())
            return cls.getDeclaredConstructor().newInstance() as GrammarEngine
        } catch (e: ClassNotFoundException) {
            // The ordinary "built without the engine" case.
            check(!required) { "NQP_JVM_TRUFFLE=require, but $IMPL is not on the class path" }
            return null
        } catch (e: ReflectiveOperationException) {
            return unavailable(e)
        } catch (e: LinkageError) {
            // Typically Truffle missing from the module path: the engine class
            // is there but cannot link. Silence here is the failure mode that
            // reads as "Truffle is slow", so say so.
            return unavailable(e)
        }
    }

    private fun unavailable(cause: Throwable): GrammarEngine? {
        if (required) throw IllegalStateException("NQP_JVM_TRUFFLE=require, but $IMPL did not load", cause)
        System.err.println("nqp: grammar engine unavailable, using bytecode regexes ($cause)")
        return null
    }
}
