package org.raku.nqp.runtime

import java.io.BufferedReader
import java.io.IOException
import java.io.InputStreamReader
import org.raku.nqp.io.AsyncProcessHandle
import org.raku.nqp.io.AsyncServerSocketHandle
import org.raku.nqp.io.AsyncSocketHandle
import org.raku.nqp.sixmodel.SixModelObject
import org.raku.nqp.sixmodel.reprs.AsyncTaskInstance
import org.raku.nqp.sixmodel.reprs.IOHandleInstance

/**
 * Async / signal ops. Generated bytecode invokes these as statics by exact
 * descriptor (see $TYPE_IO_OPS mappings in src/vm/jvm/QAST/Compiler.nqp),
 * which @JvmStatic preserves.
 */
object IOOps {

    private class SigRunnable(val tc: ThreadContext, val schedulee: SixModelObject, val signum: Long) : Runnable {
        override fun run() {
            Ops.invokeDirect(tc, schedulee, Ops.invocantCallSite,
                arrayOf<Any?>(Ops.box_i(signum, tc.frame.codeRef.staticInfo.compUnit.hllConfig.intBoxType, tc)))
        }
    }

    /* Registered signal schedulees, run by one JVM shutdown hook installed on
     * first use. The Java original registered a hook per signal() call, which
     * parked a Thread -- and the ThreadContext its runnable held, and through
     * it the run's whole GlobalContext -- in ApplicationShutdownHooks until
     * the JVM died; its handler state also lived in statics, so a later
     * registration overwrote every earlier one. The registry is cleared with
     * the dispatch caches between eval-server runs, so a finished run's
     * handlers neither pin the run nor fire at server exit. */
    private val signalRuns = java.util.concurrent.CopyOnWriteArrayList<SigRunnable>()
    private val signalHooked = java.util.concurrent.atomic.AtomicBoolean(false)

    private object SigProcess {
        private const val SIGNUM_HIGHEST = 32

        private val sigSupported: Map<String, Int> =
            listOf("SIGINT", "SIGKILL").associateWith { 1 }

        val sigKeys: List<String> = listOf(
            "SIGHUP",  "SIGINT",    "SIGQUIT",   "SIGILL",   "SIGTRAP", "SIGABRT",
            "SIGEMT",  "SIGFPE",    "SIGKILL",   "SIGBUS",   "SIGSEGV", "SIGSYS",
            "SIGPIPE", "SIGALRM",   "SIGTERM",   "SIGURG",   "SIGSTOP", "SIGTSTP",
            "SIGCONT", "SIGCHLD",   "SIGTTIN",   "SIGTTOU",  "SIGIO",   "SIGXCPU",
            "SIGXFSZ", "SIGVTALRM", "SIGPROF",   "SIGWINCH", "SIGINFO", "SIGUSR1",
            "SIGUSR2", "SIGTHR",    "SIGSTKFLT", "SIGPWR",   "SIGBREAK",
        )

        private fun getNameFromVal(signum: Int): String? {
            // Use sh kill builtin, seems most portable across MacOSX, and Linux and BSD variants
            val shArg = "kill -l $signum"
            val pb = ProcessBuilder("sh", "-c", shArg)
            try {
                var retval = -1
                var finished = false

                val process = pb.start()
                do {
                    try {
                        retval = process.waitFor()
                        finished = true
                    } catch (e: InterruptedException) {
                    }
                } while (!finished)
                if (retval == 0) {
                    val br = BufferedReader(InputStreamReader(process.inputStream))
                    val s = br.readLine()
                    if (s != null) {
                        return "SIG" + s.trim().uppercase()
                    }
                }
            } catch (e: IOException) {
            }
            return null
        }

        private fun retrieveValsWin(sigWanted: MutableMap<String, Int>) {
            // Use same sigs defined for _WIN32 in MoarVM
            sigWanted["SIGHUP"] = 1
            sigWanted["SIGKILL"] = 9
            sigWanted["SIGWINCH"] = 28
        }

        private fun retrieveValsPosix(sigWanted: MutableMap<String, Int>) {
            var sigval: String? = ""
            var i = 1
            while (sigval != null && i <= SIGNUM_HIGHEST) {
                sigval = getNameFromVal(i)
                if (sigval != null && sigWanted.containsKey(sigval)) {
                    sigWanted[sigval] = i
                }
                i++
            }
        }

        fun process(): Map<String, Int> {
            val sigWanted = HashMap<String, Int>()
            for (k in sigKeys) sigWanted[k] = 0

            // Get available signals on host system
            val os = System.getProperty("os.name").lowercase()
            if (os.indexOf("win") >= 0) {
                retrieveValsWin(sigWanted)
            } else {
                retrieveValsPosix(sigWanted)
            }

            // Negate sigs not supported by backend
            for (sig in sigWanted.keys) {
                val signum = sigWanted.getValue(sig)
                sigWanted[sig] = if (sigSupported.containsKey(sig)) signum else -signum
            }
            return sigWanted
        }
    }

    private var sigCache: SixModelObject? = null

    @JvmStatic
    fun getsignals(tc: ThreadContext): SixModelObject {
        if (Ops.isnull(sigCache) == 0L) return sigCache!!

        val listType = tc.frame.codeRef.staticInfo.compUnit.hllConfig.listType!!
        val strType = tc.frame.codeRef.staticInfo.compUnit.hllConfig.strBoxType
        val intType = tc.frame.codeRef.staticInfo.compUnit.hllConfig.intBoxType
        val res = listType.st.REPR.allocate(tc, listType.st)

        val sigWanted = SigProcess.process()

        // Box the list values for HLL
        for (sig in SigProcess.sigKeys) {
            val signum = sigWanted.getValue(sig).toLong()
            res.push_boxed(tc, Ops.box_s(sig, strType, tc))
            res.push_boxed(tc, Ops.box_i(signum, intType, tc))
        }
        sigCache = res
        return res
    }

    @JvmStatic
    fun signal(queue: SixModelObject, schedulee: SixModelObject,
               signalNum: Long, asyncType: SixModelObject, tc: ThreadContext): SixModelObject {
        when (signalNum.toInt()) {
            2 -> {} // INT
            9 -> {} // KILL
            else -> ExceptionHandling.dieInternal(tc, "Unsupported signal $signalNum")
        }
        val task = asyncType.st.REPR.allocate(tc, asyncType.st) as AsyncTaskInstance
        task.queue = queue
        task.schedulee = schedulee

        if (signalHooked.compareAndSet(false, true)) {
            Runtime.getRuntime().addShutdownHook(Thread {
                for (sigrun in signalRuns)
                    sigrun.run()
            })
            org.raku.nqp.dispatch.DispatchBootstrap.registerResettable { signalRuns.clear() }
        }
        signalRuns.add(SigRunnable(tc, schedulee, signalNum))
        return task
    }

    @JvmStatic
    fun watchfile(queue: SixModelObject, schedulee: SixModelObject,
                  filename: String, asyncType: SixModelObject, tc: ThreadContext): SixModelObject {
        throw UnsupportedOperationException("watchfile is not yet implemented.")
    }

    @JvmStatic
    fun asyncconnect(queue: SixModelObject, schedulee: SixModelObject,
                     host: String, port: Long, asyncType: SixModelObject, tc: ThreadContext): SixModelObject {
        val task = asyncType.st.REPR.allocate(tc, asyncType.st) as AsyncTaskInstance
        task.queue = queue
        task.schedulee = schedulee

        val handle = AsyncSocketHandle(tc)
        task.handle = handle
        handle.connect(tc, host, port.toInt(), task)

        return task
    }

    @JvmStatic
    fun asynclisten(queue: SixModelObject, schedulee: SixModelObject,
                    host: String, port: Long, backlog: Long, asyncType: SixModelObject, tc: ThreadContext): SixModelObject {
        val task = asyncType.st.REPR.allocate(tc, asyncType.st) as AsyncTaskInstance
        task.queue = queue
        task.schedulee = schedulee

        val handle = AsyncServerSocketHandle(tc)
        task.handle = handle

        handle.bind(tc, host, port.toInt(), backlog.toInt())
        handle.accept(tc, task)

        return task
    }

    @JvmStatic
    fun asyncwritebytes(handle: SixModelObject, queue: SixModelObject,
                        schedulee: SixModelObject, toWrite: SixModelObject, asyncType: SixModelObject,
                        tc: ThreadContext): SixModelObject {
        val task = asyncType.st.REPR.allocate(tc, asyncType.st) as AsyncTaskInstance
        task.queue = queue
        task.schedulee = schedulee
        task.handle = (handle as IOHandleInstance).handle

        when (val taskHandle = task.handle) {
            is AsyncSocketHandle -> taskHandle.writeBytes(tc, task, toWrite)
            is AsyncProcessHandle -> taskHandle.writeBytes(tc, task, toWrite)
            else -> throw ExceptionHandling.dieInternal(tc, "This handle does not support asyncwritebytes")
        }
        return task
    }

    @JvmStatic
    fun asyncreadbytes(handle: SixModelObject, queue: SixModelObject,
                       schedulee: SixModelObject, bufType: SixModelObject, asyncType: SixModelObject,
                       tc: ThreadContext): SixModelObject {
        val task = asyncType.st.REPR.allocate(tc, asyncType.st) as AsyncTaskInstance
        task.queue = queue
        task.schedulee = schedulee
        task.handle = (handle as IOHandleInstance).handle

        when (val taskHandle = task.handle) {
            is AsyncSocketHandle -> taskHandle.readBytes(tc, task, bufType)
            else -> throw ExceptionHandling.dieInternal(tc, "This handle does not support asyncreadbytes")
        }
        return task
    }

    @JvmStatic
    fun spawnprocasync(queue: SixModelObject, prog: String,
                       args: SixModelObject, cwd: String, env: SixModelObject, config: SixModelObject,
                       tc: ThreadContext): SixModelObject {
        val hllConfig = tc.frame.codeRef.staticInfo.compUnit.hllConfig
        val ioType = hllConfig.ioType!!
        val ioHandle = ioType.st.REPR.allocate(tc, ioType.st) as IOHandleInstance
        ioHandle.handle = AsyncProcessHandle(tc, queue, prog, args, cwd, env, config)
        return ioHandle
    }

    @JvmStatic
    fun killprocasync(handle: SixModelObject, signal: Long, tc: ThreadContext): Long {
        when (signal.toInt()) {
            // SIGHUP (default used by Rakudo for 'kill'), SIGTERM
            1, 15 -> ((handle as IOHandleInstance).handle as AsyncProcessHandle).kill(tc)
            // SIGKILL
            9 -> ((handle as IOHandleInstance).handle as AsyncProcessHandle).killForcibly(tc)
            else -> throw ExceptionHandling.dieInternal(tc, "Unsupported signal for kill: $signal")
        }
        return signal
    }
}
